application/src/Entity/ProductInventory.php
<?php

namespace App\Entity;

use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductInventoryRepository")
 */
class ProductInventory
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Product", inversedBy="productInventories")
     * @ORM\JoinColumn(nullable=false)
     */
    private $product;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Provider", inversedBy="productInventories")
     */
    private $provider;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Platform", inversedBy="productInventories")
     */
    private $platform;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $code;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="productInventories")
     */
    private $claimed_by;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $date_created;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $date_updated;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $date_claimed;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_active;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_enabled;

    public function __construct()
    {
        $this->date_created = new DateTimeImmutable();
        $this->date_updated = new DateTimeImmutable();
        $this->is_active = false;
        $this->is_enabled = true;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getProvider(): ?Provider
    {
        return $this->provider;
    }

    public function setProvider(?Provider $provider): self
    {
        $this->provider = $provider;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): self
    {
        $this->url = $url;

        return $this;
    }

    /**
     * @return Platform
     */
    public function getPlatform(): ?Platform
    {
        return $this->platform;
    }

    public function setPlatform(?Platform $platform): self
    {
        $this->platform = $platform;

        return $this;
    }


    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(?string $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getClaimedBy(): ?User
    {
        return $this->claimed_by;
    }

    public function setClaimedBy(?User $claimed_by): self
    {
        $this->claimed_by = $claimed_by;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getDateCreated(): ?DateTimeImmutable
    {
        return $this->date_created;
    }

    public function setDateCreated(DateTimeImmutable $date_created): self
    {
        $this->date_created = $date_created;

        return $this;
    }

    public function getDateUpdated(): ?DateTimeImmutable
    {
        return $this->date_updated;
    }

    public function setDateUpdated(DateTimeImmutable $date_updated): self
    {
        $this->date_updated = $date_updated;

        return $this;
    }

    public function getDateClaimed(): ?DateTimeImmutable
    {
        return $this->date_claimed;
    }

    public function setDateClaimed(?DateTimeImmutable $date_claimed): self
    {
        $this->date_claimed = $date_claimed;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getIsEnabled(): ?bool
    {
        return $this->is_enabled;
    }

    public function setIsEnabled(bool $is_enabled): self
    {
        $this->is_enabled = $is_enabled;

        return $this;
    }
}

application/src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Entity\ProductInventory;
use App\Repository\ProductInventoryRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class DefaultController extends AbstractController
{


    /**
     * @Route("/", name="home")
     * @return Response
     */
    public function index(): Response
    {
        return $this->render("default/layout.html.twig");
    }

    /**
     * @Route("/giveaways", name="giveaways")
     * @return Response
     */
    public function giveaways(): Response
    {
        /** @var ProductInventoryRepository $pi_repository */
        $pi_repository = $this->getDoctrine()->getRepository(ProductInventory::class);
        $items = $pi_repository->findAllAvailable();


        return $this->render('default/pages/giveaway.html.twig', [
            'items' => $items
        ]);
    }

    /**
     * @Route("/about", name="about")
     * @return Response
     */
    public function about(): Response
    {
        return $this->render('default/pages/about.html.twig');
    }


    /**
     * @Route("/tests")
     */
    public function tests(): Response
    {
        $number = random_int(0, 100);
        return $this->render('examples/test.html.twig', [
            'number' => $number,
        ]);
    }

    /**
     * @Route("/blog")
     */
    public function blog(): Response
    {
        $number = random_int(0, 100);
        return $this->render('examples/blog.html.twig', [
            'number' => $number,
        ]);
    }

    /**
     * @Route("/lucky/number")
     */
    public function number()
    {
        $number = random_int(0, 100);

        return new Response(
            '<html><body>Lucky number: ' . $number . '</body></html>'
        );
    }
}

application/templates/default/pages/about.html.twig
{% extends 'default/layout.html.twig' %}

{% block content %}
    <h1>Here comes about section</h1>
{% endblock content %}

application/templates/default/pages/games.html.twig
{% extends 'default/layout.html.twig' %}

{% block content %}
    <div class="row">
        <h1>Simple Phaser test</h1>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div id="game"></div>
        </div>
    </div>
{% endblock content %}

{% block title %}
    Phaser 3 Game - test that works
{% endblock %}

{% block javascripts %}
    <script src="//cdn.jsdelivr.net/npm/phaser@3.16.2/dist/phaser.js"></script>
    <script>
        var config = {
            type: Phaser.AUTO,
            width: 800,
            height: 600,
            parent: "game",
            physics: {
                default: 'arcade',
                arcade: {
                    gravity: {y: 200}
                }
            },
            scene: {
                preload: preload,
                create: create
            }
        };

        var game = new Phaser.Game(config);

        function preload() {
            this.load.setBaseURL('http://labs.phaser.io');

            this.load.image('sky', 'assets/skies/space3.png');
            this.load.image('logo', 'assets/sprites/phaser3-logo.png');
            this.load.image('red', 'assets/particles/red.png');
        }

        function create() {
            this.add.image(400, 300, 'sky');

            var particles = this.add.particles('red');

            var emitter = particles.createEmitter({
                speed: 100,
                scale: {start: 1, end: 0},
                blendMode: 'ADD'
            });

            var logo = this.physics.add.image(400, 100, 'logo');

            logo.setVelocity(100, 200);
            logo.setBounce(1, 1);
            logo.setCollideWorldBounds(true);

            emitter.startFollow(logo);
        }
    </script>
{% endblock javascripts %}

application/templates/default/pages/giveaway.html.twig
{% extends 'default/layout.html.twig' %}



{% block content %}
    <div class="row">
        <h1>Here comes possible giveaway list</h1>
    </div>

    <div class="row">
        <div class="col-md-12">
            {% for item in items %}
                <div class="row">
                    <div class="col-md-3">{{ item.product.name }}</div>
                    <div class="col-md-1">{{ item.product.type.name }}</div>
                    <div class="col-md-2">
                        <a href="{{ item.provider.url }}">{{ item.provider.name }}</a>
                    </div>
                    <div class="col-md-1">{{ item.provider.type.name }}</div>
                    <div class="col-md-1">
                        <a href=" {{ item.url }}">Link</a></div>
                    <div class="col-md-2">
                        {{ item.platform.name }}
                    </div>
                    <div class="col-md-2">{{ item.dateCreated|date }}</div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock content %}